---
- name: Installer et configurer Zabbix Agent sur Linux (Debian/Ubuntu)
  hosts: tag__Linux_Server
  become: yes
  vars:
    zabbix_server: "10.0.10.70"
  tasks:

    - name: Installer Zabbix Agent (Debian/Ubuntu)
      apt:
        name: zabbix-agent
        state: present
      when: ansible_os_family == "Debian"

    - name: Configurer Zabbix Agent
      template:
        src: test.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify: Restart Zabbix Agent

  handlers:
    - name: Restart Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted
