---
- name: Installer et configurer Zabbix Agent sur Windows
  hosts: tag__Windows_Server
  tasks:
   vars:
    zabbix_server: "10.0.10.70"
    - name: Télécharger et installer Zabbix Agent
      win_package:
        path: "https://cdn.zabbix.com/zabbix/binaries/stable/latest/zabbix_agent-6.0.0.msi"
        state: present

    - name: Configurer Zabbix Agent
      win_template:
        src: zabbix_agentd.conf.j2
        dest: "C:\\Program Files\\Zabbix Agent\\zabbix_agentd.conf"

    - name: Redémarrer le service Zabbix Agent
      win_service:
        name: "Zabbix Agent"
        state: restarted
